// <auto-generated />
using DNIC.Erechtheion.Core.EnumTypes;
using DNIC.Erechtheion.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace DNIC.Erechtheion.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ErechtheionDbContext))]
    [Migration("20180423160751_Erechtheion")]
    partial class Erechtheion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DNIC.Erechtheion.Domain.Entities.AbstractContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChannelId");

                    b.Property<string>("Content");

                    b.Property<int>("ContentType");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<int>("DenyCount");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int>("LikeCount");

                    b.Property<string>("Slug");

                    b.Property<int>("State");

                    b.Property<string>("Title");

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("AbstractContent");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AbstractContent");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.Entities.Analytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BgColor")
                        .HasMaxLength(100);

                    b.Property<int?>("ChannelId");

                    b.Property<string>("Class")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<bool>("Enabled");

                    b.Property<string>("Icon")
                        .HasMaxLength(100);

                    b.Property<string>("ImageClass")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Link")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Order");

                    b.Property<int>("ParentId");

                    b.Property<string>("Slug")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.ValueObjects.ContentChannels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AbstractContentId");

                    b.Property<long>("ChannelId");

                    b.Property<string>("ChannelName");

                    b.HasKey("Id");

                    b.HasIndex("AbstractContentId");

                    b.ToTable("ContentChannels");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.Entities.Topic", b =>
                {
                    b.HasBaseType("DNIC.Erechtheion.Domain.Entities.AbstractContent");

                    b.Property<bool>("Enabled");

                    b.Property<bool>("Locked");

                    b.ToTable("Topic");

                    b.HasDiscriminator().HasValue("Topic");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.Entities.AbstractContent", b =>
                {
                    b.HasOne("DNIC.Erechtheion.Domain.Entities.Channel")
                        .WithMany("Contents")
                        .HasForeignKey("ChannelId");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.Entities.Channel", b =>
                {
                    b.HasOne("DNIC.Erechtheion.Domain.Entities.Channel")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ChannelId");
                });

            modelBuilder.Entity("DNIC.Erechtheion.Domain.ValueObjects.ContentChannels", b =>
                {
                    b.HasOne("DNIC.Erechtheion.Domain.Entities.AbstractContent")
                        .WithMany("Channels")
                        .HasForeignKey("AbstractContentId");
                });
#pragma warning restore 612, 618
        }
    }
}
